package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.BuildType
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.gradle
import jetbrains.buildServer.configs.kotlin.v2019_2.triggers.vcs
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with id = 'TestsMetadata_TestMetadataDemo'
in the project with id = 'TestsMetadata', and delete the patch script.
*/
create(RelativeId("TestsMetadata"), BuildType({
    id("TestsMetadata_TestMetadataDemo")
    name = "5. Test metadata demo"

    artifactRules = "build/reports/tests/test => gradle_test_report.zip"

    params {
        param("teamcity.build.serviceMessages.logOriginal", "true")
    }

    vcs {
        root(RelativeId("TestsMetadata_GitGithubComJetBrainsTeamcityTestMetadataDemoGitRefsHeadsMaster"))
    }

    steps {
        gradle {
            tasks = "clean build"
            buildFile = ""
            gradleWrapperPath = ""
        }
    }

    triggers {
        vcs {
        }
    }
}))

