package patches.projects

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.Project
import jetbrains.buildServer.configs.kotlin.v2019_2.projectFeatures.versionedSettings
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a project with id = 'TestsMetadata'
in the root project, and delete the patch script.
*/
create(DslContext.projectId, Project({
    id("TestsMetadata")
    name = "5. Tests Metadata"

    features {
        versionedSettings {
            id = "PROJECT_EXT_1"
        }
    }
}))

