package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*
import jetbrains.buildServer.configs.kotlin.v2019_2.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a vcsRoot with id = 'TestsMetadata_GitGithubComJetBrainsTeamcityTestMetadataDemoGitRefsHeadsMaster'
in the project with id = 'TestsMetadata', and delete the patch script.
*/
create(RelativeId("TestsMetadata"), GitVcsRoot({
    id("TestsMetadata_GitGithubComJetBrainsTeamcityTestMetadataDemoGitRefsHeadsMaster")
    name = "git@github.com:JetBrains/teamcity-test-metadata-demo.git#refs/heads/master"
    url = "git@github.com:JetBrains/teamcity-test-metadata-demo.git"
    branch = "refs/heads/master"
    branchSpec = "refs/heads/*"
    authMethod = uploadedKey {
        userName = "git"
        uploadedKey = "id_rsa"
    }
}))

